<?php

/**
 * Implementation of hook_block_info
 */
function available_courses_block_info() 
  {
  $blocks['available_courses']=array
    (
    'info' => t('Available Courses'),
    'weight' => 1,
    );
  return($blocks); 
  } // end function available_courses_block_info() 

/**
 * Implementation of hook_block_view
 */
function available_courses_block_view($delta="")
  {
  $block = array();
  switch ($delta)
    {
    case "register":
      $block['subject'] = t('Available Courses');
      $block['content'] = available_courses();
      break;
      
    default:
      $block['subject'] = t('Available Courses');
      $block['content'] = available_courses();
      break;
    }// end switch ($delta)
  return($block);
  }// end function available_courses_block_view($delta="")
  
/**
 * function to return register form
 */
function available_courses() 
  {
  $content = '';
  $content .= "<p>The following courses are available to register for:</p>";
  $content .= "<table border='1'>\r\n
               <tr>
               <th>ID Number</th>
               <th>Title</th>
               <th>More Information</th>
               <th>Sign Up!</th>
               </tr>\r\n";

  $result = db_query("SELECT * FROM dln_course");
  while($row = $result->fetchAssoc())
    {
    extract($row);
    $content .= "<tr>";
    $content .= "<td>$course_number</td>";
    $content .= "<td>$course_title</td>";
    if($course_link!="")
      $content .= "<td>".l('Course Details',$course_link)."</td>";
    else
      $content .= "<td>&nbsp;</td>";
    $content .= "<td><form method=\"post\" action=\"/sign-up\"><input type=\"hidden\" name=\"courseID\" value=\"$course_id\" /><input type=\"submit\" value=\"Sign Up\" /></form></td>";
    $content .= "</tr>\r\n";
    }
  
  $content .= "</table>";
  return($content);
  } // end function available_courses() 
