<?php

/**
 * Implementation of hook_block_info
 */
function categories_block_info() 
  {
  $blocks['categories']=array
    (
    'info' => t('Add DLN Category'),
    'weight' => 1,
    );
  return($blocks); 
  } // end function categories_block_info() 

/**
 * Implementation of hook_block_view
 */
function categories_block_view($delta="")
  {
  $block = array();
  switch ($delta)
    {
    case "categories":
      $block['subject'] = t('DLN Category');
      $block['content'] = add_categories();
      break;
      
    default:
      $block['subject'] = t('DLN Category');
      $block['content'] = add_categories();
      break;
    }// end switch ($delta)
  return($block);
  }// end function categories_block_view($delta="")
  
/**
 * function to return categories form
 */
function add_categories() 
  {
  $content = drupal_get_form('categories_form');
  return($content);
  } // end function add_categories() 
  
/**
 * implementation of hook_form
 */
function categories_form($form, &$form_state)
  {
  $form['description']=array
    (
    '#type' => 'item',
    '#title' => t('Add the categories below. &nbsp;Items with an asterisk (*) are mandatory fields.'),
    );
  
  $form['categoriesBlock'] = array
    (
    '#type' => 'fieldset',
    '#title' => t('Category Details'),
    //'#collapsible' => TRUE,
    //'#collapsed' => FALSE,
    );
  
  $form['categoriesBlock']['cat_name'] = array
    (
    '#type' => 'textfield',
    '#title' => t('Category Name'),
    '#required' => TRUE,
    '#description' => t('Enter the name of the category here'),
    );
  
  $form['categoriesBlock']['cat_desc'] = array
    (
    '#type' => 'textarea',
    '#title' => t('Category Description'),
    '#description' => t('Enter a description of this category.'),
    '#required' => TRUE,
    );
  
  $form['submit'] = array
    (
    '#type' => 'submit',
    '#value' => t('Submit'), 
    );
  return($form);
  }// end function categories_form($form, &$form_state)
  
/**
 * implementation of hook_form_validate
 */
function categories_form_validate($form,&$form_state)
  {
  $name= check_plain($form['categoriesBlock']['cat_name']['#value']);
  if(strlen($name)<2)
    form_set_error('categories_title',t('Category Name is too short.'));
  
  $description= check_plain($form['categoriesBlock']['cat_desc']['#value']);
  if(strlen($description)<2)
    form_set_error('categories_desc',t('Category Description is too short.'));
  
  }//end function categories_form_validate($form,&$form_state)
  
/**
 * Implementation of hook_form_submit
 */
function categories_form_submit($form, &$form_state)
  {
  $name=check_plain($form['categoriesBlock']['cat_name']['#value']);
  $desc=check_plain($form['categoriesBlock']['cat_desc']['#value']);
  
  //insert into categoriess table
  $result=db_insert('dln_categories')
    ->fields(array(
      'cat_name',
      'cat_desc',
      'org_id',))
    ->values(array(
      'cat_name'=>$name,
      'cat_desc'=>$desc,
      'org_id'=>1,
      ))
    ->execute();
    
  //get the last inserted id
  $result=db_query("SELECT cat_id FROM dln_categories ORDER BY cat_id DESC LIMIT 1");
  $row=$result->fetchAssoc();
  extract($row);
 
  drupal_set_message("Category is added.");
  }//end function categories_form_submit($form, &$form_state)
