<?php

/**
 * Implementation of hook_block_info
 */
function course_reg_two_block_info() 
  {
  $blocks['course_reg_two']=array
    (
    'info' => t('Module Scheduling Part Two'),
    'weight' => 1,
    );
  return($blocks); 
  } // end function course_reg_two_block_info() 

/**
 * Implementation of hook_block_view
 */
function course_reg_two_block_view($delta="")
  {
  $block = array();
  switch ($delta)
    {
    case "reg_two":
      $block['subject'] = t('Module Scheduling Part Two');
      $block['content'] = assign_reg_two();
      break;
      
    default:
      $block['subject'] = t('Module Scheduling Part Two');
      $block['content'] = assign_reg_two();
      break;
    }// end switch ($delta)
  return($block);
  }// end function course_reg_two_block_view($delta="")
  
/**
 * function to return reg_two form
 */
function assign_reg_two() 
  {
  $content = drupal_get_form('course_reg_two_form');
  return($content);
  } // end function assign_reg_two() 
  
/**
 * implementation of hook_form
 */
function course_reg_two_form($form, &$form_state)
  {
//echo "<br /><br /><pre>".print_r($_SESSION['classroom'])."</pre><br /><br />";  
//echo "Course ID is ".$_SESSION['courseID'][0]."<br /><br />";

  $result = db_query("SELECT course_title FROM dln_course WHERE course_id='".$_SESSION['courseID'][0]."'");
  $row = $result -> fetchAssoc();
  extract($row);

  $form['description']=array
    (
    '#type' => 'item',
    '#title' => t('Locate an open slot from the schedule below for <u>'.$course_title.'</u>.'),
    );

  // first, get the first day 15 days out
  $startDate = strtotime(date("F j, Y"))+1296000;
  // next, get the last day 75 days out
  $endDate = strtotime(date("F j, Y"))+6480000;
  // create an array to hold days
  $daysArray = array();
  //Now, fill it with workdays (not Saturdays, nor Sundays, nor holidays);
  for($i=$startDate;$i<=$endDate;$i=$i+86400)
    {
    if(date("D",$i)!="Sat" && date("D",$i)!="Sun" && !is_holiday($i)) $daysArray[$i] = date("l, M jS, Y",$i);
    } 

  $form['dates_available'] = array
    (
    '#type' => 'select',
    '#options' => $daysArray,
    '#description' => t('Select which day you\'d like to have your class'),
    '#title' => t('Days Available'),
    );
  
  //build variable for mysql statement below
  $inVar = implode(",",$_SESSION['classroom']['locations']);

  // get hours and time zones of each instructor
  $result = db_query("
    SELECT a.instr_id, a.instr_loc, a.start_time_1, a.end_time_1, a.start_time_2, a.end_time_2, a.time_zone
    FROM dln_instructor a, dln_instr_course b
    WHERE a.instr_id = b.instr_id
    AND b.course_id = :courseId
    AND a.instr_loc IN ($inVar) 
    ",array(':courseId' => $_SESSION['courseID'][0]));
  //build an array of times and slots
  $timeslotArr = array();
  while($row = $result -> fetchAssoc())
    {
    extract($row);
    //echo "<br /><br />$instr_id $instr_loc $start_time_1 $end_time_1 $start_time_2 $end_time_2 $time_zone <br /><br />";
    // start determining what time slots are available:
    }
  
  $optionsArray = array
    (
    '8' => '8:00am',
    '8.5' => '8:30am',
    '9' => '9:00am',
    '9.5' => '9:30am',
    '10' => '10:00am',
    '10.5' => '10:30am',
    '11' => '11:00am',
    '11.5' => '11:30am',
    '12' => '12:00pm',
    '12.5' => '12:30pm',
    '13' => '1:00pm',
    '13.5' => '1:30pm',
    '14' => '2:00pm',
    '14.5' => '2:30pm',
    '15' => '3:00pm',
    );

  $form['start_time'] = array
    (
    '#type' => 'select',
    '#options' => $optionsArray,
    '#title' => t('Start Time'),
    '#description' => t('Select the time you\'d like to start'),
    );

  $optionsArray = array
    (
    '30' => '30 minutes',
    '45' => '45 minutes',
    '60' => '1 hour',
    );

  $form['duration'] = array
    (
    '#type' => 'select',
    '#options' => $optionsArray,
    '#title' => t('Duration'),
    '#description' => t('How long would you like the class to go for?'),
    );

  $form['submit'] = array
    (
    '#type' => 'submit',
    '#value' => t('Submit'), 
    );
  return($form);

  }// end function course_reg_two_form($form, &$form_state)
  
/**
 * implementation of hook_form_validate
 */
function course_reg_two_form_validate($form,&$form_state)
  {
  }//end function course_reg_two_form_validate($form,&$form_state)
  
/**
 * Implementation of hook_form_submit
 */
function course_reg_two_form_submit($form, &$form_state)
  {
  $duration = $form['duration']['#value']." minutes";
  // Not sure why, but date is being stored one day later and one hour earlier.  So we subtract 23 hours... 
  $timestamp = $form['dates_available']['#value'] - 82800 + $form['start_time']['#value'] * 3600;  
  $locID = array_pop($_SESSION['classroom']['locations']); 

  $gr = $_SESSION['classroom']['range'];

  $result = db_query("SELECT course_title FROM dln_course WHERE course_id='".$_SESSION['courseID'][0]."'");
  $row = $result -> fetchAssoc();
  extract($row);

  $result = db_query("SELECT loc_name FROM dln_location WHERE loc_id='$locID'");
  $row=$result->fetchAssoc();
  extract($row);

  $details = "";
  $details .= "<p>School: ".$_SESSION['classroom']['school']." </p>";
  $details .= "<p>State: ".$_SESSION['classroom']['state']." </p>";
 
  //insert into events table
  $result=db_insert('events')
    ->fields(array(
      'event_title',
      'event_type',
      'event_details',
      'event_timestamp',
      'event_location',
      'contact_name',
      'contact_email',
      'contact_phone',
      'event_duration',
      'webinar',
      'slot',
      'approved',
      'timezone',
      'age_range',
      'instructor',
      ))
    ->values(array(
      'event_title' => $course_title,
      'event_type' => "Internet Class",
      'event_details' => $details,
      'event_timestamp' => $timestamp,
      'event_location' => $loc_name,
      'contact_name' => $_SESSION['classroom']['teacher'],
      'contact_email' => $_SESSION['classroom']['email'],
      'contact_phone' => $_SESSION['classroom']['phone'],
      'event_duration' => $duration,
      'webinar' => "",
      'slot' => 1,
      'approved' => "N",
      'timezone' => $_SESSION['classroom']['timezone'],
      'age_range' => "$gr",
      'instructor' => "",
      ))
    ->execute();
  drupal_set_message("Your course has been requested and it tentatively blocked on the <a href=\"/training-calendar\">Calendar of Events</a>.  Your request will be reviewed and you will be notified whether it is approved or not.");
  }//end function course_reg_two_form_submit($form, &$form_state)
