<?php

/**
 * Implementation of hook_block_info
 */
function course_delete_block_info() 
  {
  $blocks['course_delete']=array
    (
    'info' => t('Delete DLN Course'),
    'weight' => 1,
    );
  return($blocks); 
  } // end function course_delete_block_info() 

/**
 * Implementation of hook_block_view
 */
function course_delete_block_view($delta="")
  {
  $block = array();
  switch ($delta)
    {
    case "course_delete":
      $block['subject'] = t('Delete a DLN Course');
      $block['content'] = add_course_delete();
      break;
      
    default:
      $block['subject'] = t('Delete a DLN Course');
      $block['content'] = add_course_delete();
      break;
    }// end switch ($delta)
  return($block);
  }// end function course_delete_block_view($delta="")
  
/**
 * function to return doc_upload form
 */
function add_course_delete() 
  {
  $content = drupal_get_form('course_delete_form');
  return($content);
  } // end function add_course_delete() 
  
/**
 * implementation of hook_form
 */
function course_delete_form($form, &$form_state)
  {
  $form['description']=array
    (
    '#type' => 'item',
    '#title' => t('Delete your course below. &nbsp;Items with an asterisk (*) are mandatory fields.'),
    );
  
  $form['course_deleteBlock'] = array
    (
    '#type' => 'fieldset',
    '#title' => t('Course to Delete'),
    //'#collapsible' => TRUE,
    //'#collapsed' => FALSE,
    );
  
  $optionsArray = array();
  $results = db_query("SELECT * FROM dln_course");
  while($row = $results -> fetchAssoc())
    {
    extract($row);
    $optionsArray[$course_id] = $course_number . " - " .$course_title;
    }
  $form['course_deleteBlock']['course_id']=array
    (
    '#type' => 'select',
    '#title' => t('Course to Delete'),
    '#options' => $optionsArray,
    '#description' => t('Select the course to delete.'),
    );

  $form['submit'] = array
    (
    '#type' => 'submit',
    '#value' => t('DELETE'), 
    );
  return($form);
  }// end function course_delete_form($form, &$form_state)
  
  
/**
 * Implementation of hook_form_submit
 */
function course_delete_form_submit($form, &$form_state)
  {
  $id = $form['course_deleteBlock']['course_id']['#value'];
  
  //insert into course_deletes table
  $result=db_query("DELETE from dln_course WHERE course_id='$id'");
 
  drupal_set_message("Course is deleted.");
  }//end function course_delete_form_submit($form, &$form_state)
