<?php

/**
 * Implementation of hook_block_info
 */
function dln_admin_delete_block_info() 
  {
  $blocks['dln_admin_delete']=array
    (
    'info' => t('Delete DLN Administrator'),
    'weight' => 1,
    );
  return($blocks); 
  } // end function dln_admin_delete_block_info() 

/**
 * Implementation of hook_block_view
 */
function dln_admin_delete_block_view($delta="")
  {
  $block = array();
  switch ($delta)
    {
    case "dln_admin_delete":
      $block['subject'] = t('Delete a DLN Administrator');
      $block['content'] = add_dln_admin_delete();
      break;
      
    default:
      $block['subject'] = t('Delete a DLN Administrator');
      $block['content'] = add_dln_admin_delete();
      break;
    }// end switch ($delta)
  return($block);
  }// end function dln_admin_delete_block_view($delta="")
  
/**
 * function to return doc_upload form
 */
function add_dln_admin_delete() 
  {
  $content = drupal_get_form('dln_admin_delete_form');
  return($content);
  } // end function add_dln_admin_delete() 
  
/**
 * implementation of hook_form
 */
function dln_admin_delete_form($form, &$form_state)
  {
  $form['description']=array
    (
    '#type' => 'item',
    '#title' => t('Delete your adminstrator below. &nbsp;Items with an asterisk (*) are mandatory fields.'),
    );
  
  $form['dln_admin_deleteBlock'] = array
    (
    '#type' => 'fieldset',
    '#title' => t('Administrator to Delete'),
    //'#collapsible' => TRUE,
    //'#collapsed' => FALSE,
    );
  
  $optionsArray = array();
  $results = db_query("SELECT * FROM dln_admin");
  while($row = $results -> fetchAssoc())
    {
    extract($row);
    $optionsArray[$admin_id] = $admin_name;
    }
  $form['dln_admin_deleteBlock']['dln_admin_id']=array
    (
    '#type' => 'select',
    '#title' => t('Administrator to Delete'),
    '#options' => $optionsArray,
    '#description' => t('Select the dln_admin to delete.'),
    );

  $form['submit'] = array
    (
    '#type' => 'submit',
    '#value' => t('DELETE'), 
    );
  return($form);
  }// end function dln_admin_delete_form($form, &$form_state)
  
  
/**
 * Implementation of hook_form_submit
 */
function dln_admin_delete_form_submit($form, &$form_state)
  {
  $id = $form['dln_admin_deleteBlock']['dln_admin_id']['#value'];
  
  //insert into dln_admin_deletes table
  $result=db_query("DELETE from dln_admin WHERE admin_id='$id'");
 
  drupal_set_message("Administrator is deleted.");
  }//end function dln_admin_delete_form_submit($form, &$form_state)
