<?php

/**
 * Implementation of hook_block_info
 */
function instructor_delete_block_info() 
  {
  $blocks['instructor_delete']=array
    (
    'info' => t('Delete DLN Instructor'),
    'weight' => 1,
    );
  return($blocks); 
  } // end function instructor_delete_block_info() 

/**
 * Implementation of hook_block_view
 */
function instructor_delete_block_view($delta="")
  {
  $block = array();
  switch ($delta)
    {
    case "instructor_delete":
      $block['subject'] = t('Delete a DLN Instructor');
      $block['content'] = add_instructor_delete();
      break;
      
    default:
      $block['subject'] = t('Delete a DLN Instructor');
      $block['content'] = add_instructor_delete();
      break;
    }// end switch ($delta)
  return($block);
  }// end function instructor_delete_block_view($delta="")
  
/**
 * function to return doc_upload form
 */
function add_instructor_delete() 
  {
  $content = drupal_get_form('instructor_delete_form');
  return($content);
  } // end function add_instructor_delete() 
  
/**
 * implementation of hook_form
 */
function instructor_delete_form($form, &$form_state)
  {
  $form['description']=array
    (
    '#type' => 'item',
    '#title' => t('Delete your instructor below. &nbsp;Items with an asterisk (*) are mandatory fields.'),
    );
  
  $form['instructor_deleteBlock'] = array
    (
    '#type' => 'fieldset',
    '#title' => t('Instructor to Delete'),
    //'#collapsible' => TRUE,
    //'#collapsed' => FALSE,
    );
  
  $optionsArray = array();
  $results = db_query("SELECT * FROM dln_instructor");
  while($row = $results -> fetchAssoc())
    {
    extract($row);
    $optionsArray[$instr_id] = $instr_name;
    }
  $form['instructor_deleteBlock']['instructor_id']=array
    (
    '#type' => 'select',
    '#title' => t('Instructor to Delete'),
    '#options' => $optionsArray,
    '#description' => t('Select the instructor to delete.'),
    );

  $form['submit'] = array
    (
    '#type' => 'submit',
    '#value' => t('DELETE'), 
    );
  return($form);
  }// end function instructor_delete_form($form, &$form_state)
  
  
/**
 * Implementation of hook_form_submit
 */
function instructor_delete_form_submit($form, &$form_state)
  {
  $id = $form['instructor_deleteBlock']['instructor_id']['#value'];
  
  //insert into instructor_deletes table
  $result=db_query("DELETE from dln_instructor WHERE instr_id='$id'");
 
  drupal_set_message("Instructor is deleted.");
  }//end function instructor_delete_form_submit($form, &$form_state)
