<?php

/**
 * Implementation of hook_block_info
 */
function school_block_info() 
  {
  $blocks['school']=array
    (
    'info' => t('Subscriber School Info'),
    'weight' => 1,
    );
  return($blocks); 
  } // end function school_block_info() 

/**
 * Implementation of hook_block_view
 */
function school_block_view($delta="")
  {
  $block = array();
  switch ($delta)
    {
    case "school":
      $block['subject'] = t('Add a school');
      $block['content'] = add_school();
      break;
      
    default:
      $block['subject'] = t('Add a School');
      $block['content'] = add_school();
      break;
    }// end switch ($delta)
  return($block);
  }// end function school_block_view($delta="")
  
/**
 * function to return school form
 */
function add_school() 
  {
  $content = drupal_get_form('school_form');
  return($content);
  } // end function add_school() 
  
/**
 * implementation of hook_form
 */
function school_form($form, &$form_state)
  {
  $form['description']=array
    (
    '#type' => 'item',
    '#name' => t('Add your school (or learning group) information below. &nbsp;Items with an asterisk (*) are mandatory fields.'),
    );
  
  $form['schoolBlock'] = array
    (
    '#type' => 'fieldset',
    '#name' => t('School (Learning Group) Details'),
    //'#collapsible' => TRUE,
    //'#collapsed' => FALSE,
    );

  $optionsArray = array
    (
    'Alabama' => 'AL',
    'Alaska' => 'AK',
    'Arizona' => 'AZ',
    'Arkansas' => 'AR',
    'California' => 'CA',
    'Colorado' => 'CO',
    'Connecticut' => 'CT',
    'Delaware' => 'DE',
    'District of Columbia' => 'DC',
    'Florida' => 'FL',
    'Georgia' => 'GA',
    'Hawaii' => 'HI',
    'Idaho' => 'ID',
    'Illinois' => 'IL',
    'Indiana' => 'IN',
    'Iowa' => 'IA',
    'Kansas' => 'KS',
    'Kentucky' => 'KY',
    'Louisiana' => 'LA',
    'Maine' => 'ME',
    'Maryland' => 'MD',
    'Massachusetts' => 'MA',
    'Michigan' => 'MI',
    'Minnesota' => 'MN',
    'Mississippi' => 'MS',
    'Missouri' => 'MO',
    'Montana' => 'MT',
    'Nebraska' => 'NE',
    'Nevada' => 'NV',
    'New Hampshire' => 'NH',
    'New Jersey' => 'NJ',
    'New Mexico' => 'NM',
    'New York' => 'NY',
    'North Carolina' => 'NC',
    'North Dakota' => 'ND',
    'Ohio' => 'OH',
    'Oklahoma' => 'OK',
    'Oregon' => 'OR',
    'Pennsylvania' => 'PA',
    'Rhode Island' => 'RI',
    'South Carolina' => 'SC',
    'South Dakota' => 'SD',
    'Tennessee' => 'TN',
    'Texas' => 'TX',
    'Utah' => 'UT',
    'Vermont' => 'VT',
    'Virginia' => 'VA',
    'Washington' => 'WA',
    'West Virginia' => 'WV',
    'Wisconsin' => 'WI',
    'Wyoming' => 'WY',
    'American Samoa' => 'AS',
    'Guam' => 'GU',
    'Northern Mariana Islands' => 'MP',
    'Puerto Rico' => 'PR',
    'Virgin Islands' => 'VI',
    'Federated States of Micronesia' => 'FM',
    'Marshall Islands' => 'MH',
    'Palau' => 'PW',
    );
  $form['schoolBlock']['school_state']=array
    (
    '#type' => 'select',
    '#name' => t('Classroom State (Location)'),
    '#options' => $optionsArray,
    '#description' => t('Select which state (or territory) your school or home study group is in.'),
    );
  
  $form['schoolBlock']['school_name'] = array
    (
    '#type' => 'textfield',
    '#name' => t('Your School'),
    '#required' => TRUE,
    '#description' => t('What is the name of your school or home study group?'),
    );
  
  $form['schoolBlock']['school_zipcode'] = array
    (
    '#type' => 'textfield',
    '#name' => t('School Zip Code'),
    '#required' => TRUE,
    '#description' => t('Enter the five digit Zip (postal) code of your school (or home study group) here.'),
    );
  
  $form['submit'] = array
    (
    '#type' => 'submit',
    '#value' => t('Submit'), 
    );
  return($form);
  }// end function school_form($form, &$form_state)
  
/**
 * implementation of hook_form_validate
 */
function school_form_validate($form,&$form_state)
  {
  $name = check_plain($form['schoolBlock']['school_name']['#value']);
  if(strlen($name)<2)
    form_set_error('school_name',t('School Name is too short.'));
  
  $zip = (int)$form['schoolBlock']['school_desc']['#value'];
  if($zip < 10000 || $zip > 99999)
    form_set_error('school_zipcode',t('School Zip Code is out of range.'));
  
  }//end function school_form_validate($form,&$form_state)
  
/**
 * Implementation of hook_form_submit
 */
function school_form_submit($form, &$form_state)
  {
  $name = check_plain($form['schoolBlock']['school_name']['#value']);
  $zip = (int)$form['schoolBlock']['school_zipcode']['#value'];
  
  //insert into schools table
  $result=db_insert('dln_school')
    ->fields(array(
      'school_name',
      'school_zipcode',
      'org_id',
      ))
    ->values(array(
      'school_name'=>$name,
      'school_zipcode'=>$zip,
      'org_id'=>1,
      ))
    ->execute();
    
  //get the last inserted id
  $result=db_query("SELECT school_id FROM dln_school ORDER BY school_id DESC LIMIT 1");
  $row=$result->fetchAssoc();
  extract($row);
 
  drupal_set_message("School is added.");
  }//end function school_form_submit($form, &$form_state)
