<?php

/**
 * Implementation of hook_block_info
 */
function studio_edit_block_info() 
  {
  $blocks['studio']=array
    (
    'info' => t('Edit DLN Studio Info'),
    'weight' => 1,
    );
  return($blocks); 
  } // end function studio_edit_block_info() 

/**
 * Implementation of hook_block_view
 */
function studio_edit_block_view($delta="")
  {
  $block = array();
  switch ($delta)
    {
    case "studio":
      $block['subject'] = t('Update a DLN Studio');
      $block['content'] = edit_studio();
      break;
      
    default:
      $block['subject'] = t('Update a DLN Studio');
      $block['content'] = edit_studio();
      break;
    }// end switch ($delta)
  return($block);
  }// end function studio_edit_block_view($delta="")
  
/**
 * function to return studio form
 */
function edit_studio() 
  {
  $content = drupal_get_form('studio_edit_form');
  return($content);
  } // end function edit_studio() 
  
/**
 * implementation of hook_form
 */
function studio_edit_form($form, &$form_state)
  {
  if(isset($_POST['id'])) $_SESSION['mydata'] = array((int)$_POST['id']);
  $result=db_query("SELECT * FROM dln_studio WHERE studio_id='".$_SESSION['mydata'][0]."'");
  $row = $result -> fetchAssoc();
  extract($row);

  $form['description']=array
    (
    '#type' => 'item',
    '#title' => t('Update your studio below. &nbsp;Items with an asterisk (*) are mandatory fields.'),
    );
  
  $form['studioBlock'] = array
    (
    '#type' => 'fieldset',
    '#title' => t('Studio Details'),
    //'#collapsible' => TRUE,
    //'#collapsed' => FALSE,
    );
  
  $form['studioBlock']['studio_edit_name'] = array
    (
    '#type' => 'textfield',
    '#title' => t('Studio Name'),
    '#default_value' => $studio_name,
    '#required' => TRUE,
    '#description' => t('Enter the name of the studio here'),
    );
  
  $form['studioBlock']['studio_edit_desc'] = array
    (
    '#type' => 'textfield',
    '#title' => t('Studio Description'),
    '#default_value' => $studio_desc,
    '#required' => TRUE,
    '#description' => t('Enter the details of the studio here'),
    );
  
  $loc1=$loc_id;
  $optionsArray = array();
  $results = db_query("SELECT * FROM dln_location");
  while($row = $results -> fetchAssoc())
    {
    extract($row);
    $optionsArray[$loc_id] = $loc_name;
    }
  $form['studioBlock']['studio_edit_loc']=array
    (
    '#type' => 'select',
    '#title' => t('Location of Studio'),
    '#options' => $optionsArray,
    '#default_value' => $loc1,
    '#description' => t('Select the location of the studio.'),
    );
  
  $form['submit'] = array
    (
    '#type' => 'submit',
    '#value' => t('Submit'), 
    );
  return($form);
  }// end function studio_edit_form($form, &$form_state)
  
/**
 * implementation of hook_form_validate
 */
function studio_edit_form_validate($form,&$form_state)
  {
  $title= $form['studioBlock']['studio_edit_name']['#value'];
  if(strlen($title)<2)
    form_set_error('studio_edit_title',t('Studio Name is too short.'));
  
  $description= $form['studioBlock']['studio_edit_desc']['#value'];
  if(strlen($description)<2)
    form_set_error('studio_edit_desc',t('Studio Description is too short.'));
  
  }//end function studio_edit_form_validate($form,&$form_state)
  
/**
 * Implementation of hook_form_submit
 */
function studio_edit_form_submit($form, &$form_state)
  {
  
  $name=check_plain($form['studioBlock']['studio_edit_name']['#value']);
  $desc=check_plain($form['studioBlock']['studio_edit_desc']['#value']);
  $loc=check_plain($form['studioBlock']['studio_edit_loc']['#value']);

  //insert into studios table
  $result=db_query("UPDATE dln_studio SET
      studio_name='$name',
      studio_desc='$desc',
      loc_id='$loc',
      org_id='1'
      WHERE studio_id='".$_SESSION['mydata'][0]."'");
    
  drupal_set_message("Studio is updated.");
  }//end function studio_edit_form_submit($form, &$form_state)
